### ISSUE TITLE
Subfolder game discovery

### ISSUE THREAD

**Issue by dimon8x** [valters-tomsons/Spectabis#23]
Please add an option to search iso images in subfolders.
And it would be cool have a time counter (how long I play a game last time I launched it and in total). Similar feature is in PCSX2Bonus

**Comment by FaithLV** [comment]
There's a time counter you can enable in settings, it's not really precise, but I haven't investigated it much.

**Comment by dimon8x** [comment]
Oh, yes. I found it in the latest version from GitHub. On PCSX2 site there is outdated vesion.

**Comment by valters-tomsons** [comment]
https://github.com/valters-tomsons/Spectabis/commit/e27241ab69f20067196851f78b1438c3c8c53ba4
