### ISSUE TITLE
Support for cue files

### ISSUE THREAD

**Issue by Alaharon123** [valters-tomsons/Spectabis#47]
Steps to trigger: try dragging a cue file to the program or pressing add game and navigating to a cue file

What happens when you follow the steps: can't add

what you expected to happen instead: add game

Any other information that you think could help the case: When you have a bin/cue, you're supposed to run the cue file, not the bin file.

**Comment by MediaMaquina** [comment]
PCSX2 only opens .bin files. It never opened .cue files.
.cue files re only meaningful if there are other tracks besides the data track, on PS2 there aren't.
PS1 games have those, PS2 don't.

bin is all you need.
