### ISSUE TITLE
Can't search sub-directories?

### ISSUE THREAD

**Issue by ayoits0913** [valters-tomsons/Spectabis#53]
My PS2 folder has over 100 games, and each game is placed inside a folder with it's corresponding name.

When I choose that folder to add to Spectabis, nothing happens.

I have to choose each game .iso individually

I would rather not have to drag them all out into the same folder

Is there really no way for Spectabis to search the sub-directories as well? Or am I missing something? If not, it should definitely be added

**Comment by FaithLV** [comment]
Yeah, there's currently no such functionallity :(

**Comment by valters-tomsons** [comment]
Sub directory scanning as of https://github.com/valters-tomsons/Spectabis/commit/e27241ab69f20067196851f78b1438c3c8c53ba4
