### ISSUE TITLE
Suggestion - Increase cover size

### ISSUE THREAD

**Issue by ayoits0913** [valters-tomsons/Spectabis#54]
Would be nice to have an option or slider to make the covers bigger, to match my Steam library.

**Comment by TheFantasyHero** [comment]
yes please, a cover art size slider or different size presets would be appreciated

**Comment by valters-tomsons** [comment]
As of https://github.com/valters-tomsons/Spectabis/commit/ad02c1442d227387c6eb84ebeaf85aac678c4d96, you will be able to override boxart size in `spectabis.json`
