### ISSUE TITLE
Is there a way of running an ELF file instead of ISO for one game profile?

### ISSUE THREAD

**Issue by Hadin1** [valters-tomsons/Spectabis#59]
I've been setting up Spectabis and it works great but one game (.Hack Fragment) requires an ELF to be run instead of the ISO to be able to play online and I can't figure out a way to do so or even if it's possible.  There is a PCSX2 command line argument to run elfs (--elf=(file location)) and I tried fooling around with the spectabis.ini by adding elf=(file location) which does nothing or switching iso file location to elf instead which doesn't boot anything as I expected.

Is it possible?

**Comment by valters-tomsons** [comment]
ELF supported added as of https://github.com/valters-tomsons/Spectabis/commit/a78ac965948abf38005166804df64c190a77def4
