### ISSUE TITLE
"Cannot find default PCSX2 configuration"

### ISSUE THREAD

**Issue by oryxcallotis** [valters-tomsons/Spectabis#61]
It looks like Spectabis is looking in the Documents folder for PCSX2 settings, but PCSX2 keeps everything in its own folder (by default as far as I know) now. So every time you add a game, it can't load the default settings you have and it asks you to set up everything from scratch with each game.

Not sure if there's a way to fix this, can't find an option in Spectabis that looks in a different folder for the PCSX2_ui.ini file.

**Comment by oryxcallotis** [comment]
You can fix this by either just putting the PCSX2 folder into the documents folder, or keeping it wherever it is (like another drive) and creating a symbolic link to it.

**Comment by adamfirst1986** [comment]
Pretty sure PCSX2 settings were always in the Documents folder by default
