### ISSUE TITLE
Fresh install crashes upon selecting an ISO

### ISSUE THREAD

**Issue by Tenome** [valters-tomsons/Spectabis#63]
Windows 7. After this, I can't even open the program anymore and have to delete it.

Steps:
- Set PCSX2 directory
- "Add Game"
- Select ISO
- Crash

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Spectabis.exe
  Problem Signature 02:	1.1.2.0
  Problem Signature 03:	5f25805e
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.8.3761.0
  Problem Signature 06:	5c9c6e98
  Problem Signature 07:	168e
  Problem Signature 08:	ca
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by jaimeelcarte** [comment]
This is happening to me too in Windows 10 Pro v.20H2

**Comment by snckrz** [comment]
Happening to me too, canot import any game, neither via drag and drop nor the import game button...

**Comment by snckrz** [comment]
I found the fix: The game is looking for a gameIndex.dbf, which is called gameIndex.yaml in the newest version of PCSX2. I copied the file and renamed one of them and now it works.
