### ISSUE TITLE
Update File Extension support

### ISSUE THREAD

**Issue by andercard0** [valters-tomsons/Spectabis#66]
Hi, I'm not sure if you are still accepting this kind of requests since it seems you're about to recreate a brand new Spectabis from scratch and all that; 

But, I'd like to ask you where possible to make .CHD support for spectabis. Recently, PCSX2 has added support for the file format now in the development branches I'm compressing my games into this format, but Spectabis is not recognizing it.

Cheers!

**Comment by valters-tomsons** [comment]
Will be fixed in 1.2 with https://github.com/valters-tomsons/Spectabis/commit/b51850fc191414d8b1dc737af810cbaed2dc086c

**Comment by andercard0** [comment]
> Will be fixed in 1.2 with [b51850f](https://github.com/valters-tomsons/Spectabis/commit/b51850fc191414d8b1dc737af810cbaed2dc086c)

so fast wow thank you so much!
